  events {}
  http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    client_max_body_size 500M;

   upstream app_servers {
        least_conn;
        server api:3000;
    }

  server {
    listen 80;
    server_name app.funfantasy11.com server.funfantasy11.com;

    location / {
        return 301 https://$host$request_uri;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
  }


   server {
      listen 443 ssl;
      server_name server.funfantasy11.com;

    ssl_certificate /etc/letsencrypt/live/app.funfantasy11.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.funfantasy11.com/privkey.pem;

      location / {
          proxy_pass http://app_servers;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
    }

    server {
      listen 443 ssl;
      server_name app.funfantasy11.com;
      sendfile on;


    ssl_certificate /etc/letsencrypt/live/app.funfantasy11.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.funfantasy11.com/privkey.pem;

      gzip on;
      gzip_http_version 1.1;
      gzip_disable      "MSIE [1-6]\.";
      gzip_min_length   256;
      gzip_vary         on;
      gzip_proxied      expired no-cache no-store private auth;
      gzip_types        text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
      gzip_comp_level   9;



      location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html =404;
      }
              # Serve JavaScript files with the correct MIME type
        location ~ \.js$ {
            root /usr/share/nginx/html;
            types {
                application/javascript js;
            }
        }

        # Serve CSS files with the correct MIME type
        location ~ \.css$ {
            root /usr/share/nginx/html;
            types {
                text/css css;
            }
        }
    }
  }


